export const INITIAL_ARTWORKS = [
  {
    id: '1',
    title: 'The Gilded Echoes',
    artist: 'Victor de Valance',
    artistBio: 'A 19th-century master of lighting and texture, known for his reclusive lifestyle and exclusive use of private commissions.',
    category: 'Classical',
    styleName: 'Golden Realism',
    styleDescription: 'A meticulous focus on the interplay between light and metallic surfaces, popular in late 19th-century European courts.',
    image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?q=80&w=1000&auto=format&fit=crop',
    description: 'A masterpiece exploring the play of light on gold-leaf fabrics.',
    aiValuation: '$2.5M - $3.2M',
    startingPrice: 1500000,
    currentBid: 1850000,
    highBidder: 'Vault_Custodian',
    timerSeconds: 345,
    status: 'auction'
  },
  {
    id: '2',
    title: 'Neon Synchronicity',
    artist: 'ELXRA',
    artistBio: 'A digital pioneer based in Tokyo, ELXRA blends biometric data with algorithmic aesthetics.',
    category: 'Modern',
    styleName: 'Neo-Digitalism',
    styleDescription: 'A movement where code and canvas merge, emphasizing the vibrant, glowing nature of digital existence.',
    image: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?q=80&w=1000&auto=format&fit=crop',
    description: 'A vibrant geometric abstraction reflecting the digital heartbeat of Tokyo.',
    aiValuation: '$850k - $1.1M',
    startingPrice: 500000,
    currentBid: 720000,
    highBidder: 'Private_Collector_88',
    timerSeconds: 120,
    status: 'auction'
  },
  {
    id: '3',
    title: 'Fractured Vessel',
    artist: 'Soren K.',
    artistBio: 'Emerging from the Berlin underground, Soren K. works with raw industrial materials to explore memory.',
    category: 'Emerging',
    styleName: 'Industrial Expressionism',
    styleDescription: 'Raw, gritty emotionalism using non-traditional materials like charcoal, ash, and scrap metal.',
    image: 'https://images.unsplash.com/photo-1515405299443-f71bb718616c?q=80&w=1000&auto=format&fit=crop',
    description: 'Raw, visceral expressionist study on the fragility of human memory.',
    aiValuation: '$120k - $180k',
    startingPrice: 50000,
    currentBid: 95000,
    highBidder: 'Emerging_Fund',
    timerSeconds: 56,
    status: 'auction'
  },
  {
    id: '4',
    title: 'Azure Dreamscape',
    artist: 'Isabella Moretti',
    artistBio: 'Trained in Florence, Moretti captures the spiritual essence of the Mediterranean horizon.',
    category: 'Classical',
    styleName: 'Mediterranean Luminism',
    styleDescription: 'An emphasis on atmospheric tranquility and the specific quality of seaside light.',
    image: 'https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?q=80&w=1000&auto=format&fit=crop',
    description: 'An ethereal oil painting capturing the Mediterranean coast at dawn.',
    aiValuation: '$1.8M - $2.4M',
    startingPrice: 1000000,
    currentBid: 0,
    highBidder: 'None',
    timerSeconds: 0,
    status: 'exhibition'
  },
  {
    id: '5',
    title: 'The Glitch Sovereign',
    artist: 'Kai Zen',
    artistBio: 'An anonymous entity whose work critiques the centralized nature of information.',
    category: 'Modern',
    styleName: 'Cyber-Surrealism',
    styleDescription: 'Distorted reality through the lens of digital errors and surveillance culture.',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1000&auto=format&fit=crop',
    description: 'Digital surrealism exploring digital immortality.',
    aiValuation: '$300k - $450k',
    startingPrice: 200000,
    currentBid: 0,
    highBidder: 'None',
    timerSeconds: 0,
    status: 'exhibition'
  }  ,
  {
    "id": "10",
    "title": "Painting 11",
    "artist": "Artist 11",
    "artistBio": "Bio for 11",
    "category": "Emerging",
    "styleName": "Style",
    "styleDescription": "Description",
    "image": "/images/emerging/9d67172f-3db7-44a1-8ff9-95969ad585f1.jpeg",
    "description": "A masterpiece from emerging",
    "aiValuation": " - ",
    "startingPrice": 100000,
    "currentBid": 150000,
    "highBidder": "Collector_X",
    "timerSeconds": 120,
    "status": "auction"
  }  ,
  {
    "id": "11",
    "title": "Painting 12",
    "artist": "Artist 12",
    "artistBio": "Bio for 12",
    "category": "Emerging",
    "styleName": "Style",
    "styleDescription": "Description",
    "image": "/images/emerging/d26c6ff3-8d66-47b2-8449-ef8d0d15f59e.jpeg",
    "description": "A masterpiece from emerging",
    "aiValuation": " - ",
    "startingPrice": 100000,
    "currentBid": 150000,
    "highBidder": "Collector_X",
    "timerSeconds": 120,
    "status": "auction"
  }  ,
  {
    "id": "12",
    "title": "Painting 13",
    "artist": "Artist 13",
    "artistBio": "Bio for 13",
    "category": "Emerging",
    "styleName": "Style",
    "styleDescription": "Description",
    "image": "/images/emerging/WhatsApp Image 2026-04-24 at 1.23.00 PM.jpeg",
    "description": "A masterpiece from emerging",
    "aiValuation": " - ",
    "startingPrice": 100000,
    "currentBid": 0,
    "highBidder": "None",
    "timerSeconds": 0,
    "status": "exhibition"
  }  ,
  {
    "id": "13",
    "title": "Painting 14",
    "artist": "Artist 14",
    "artistBio": "Bio for 14",
    "category": "Emerging",
    "styleName": "Style",
    "styleDescription": "Description",
    "image": "/images/emerging/WhatsApp Image 2026-04-24 at 1.24.24 PM.jpeg",
    "description": "A masterpiece from emerging",
    "aiValuation": " - ",
    "startingPrice": 100000,
    "currentBid": 0,
    "highBidder": "None",
    "timerSeconds": 0,
    "status": "exhibition"
  }  ,
  {
    "id": "14",
    "title": "Painting 15",
    "artist": "Artist 15",
    "artistBio": "Bio for 15",
    "category": "Emerging",
    "styleName": "Style",
    "styleDescription": "Description",
    "image": "/images/emerging/WhatsApp Image 2026-04-24 at 1.24.47 PM.jpeg",
    "description": "A masterpiece from emerging",
    "aiValuation": " - ",
    "startingPrice": 100000,
    "currentBid": 0,
    "highBidder": "None",
    "timerSeconds": 0,
    "status": "exhibition"
  }  ,
  {
    "id": "15",
    "title": "Painting 16",
    "artist": "Artist 16",
    "artistBio": "Bio for 16",
    "category": "Emerging",
    "styleName": "Style",
    "styleDescription": "Description",
    "image": "/images/emerging/WhatsApp Image 2026-04-24 at 1.25.53 PM.jpeg",
    "description": "A masterpiece from emerging",
    "aiValuation": " - ",
    "startingPrice": 100000,
    "currentBid": 0,
    "highBidder": "None",
    "timerSeconds": 0,
    "status": "exhibition"
  }  ,
  {
    "id": "16",
    "title": "Painting 17",
    "artist": "Artist 17",
    "artistBio": "Bio for 17",
    "category": "Emerging",
    "styleName": "Style",
    "styleDescription": "Description",
    "image": "/images/emerging/WhatsApp Image 2026-04-24 at 1.26.32 PM.jpeg",
    "description": "A masterpiece from emerging",
    "aiValuation": " - ",
    "startingPrice": 100000,
    "currentBid": 0,
    "highBidder": "None",
    "timerSeconds": 0,
    "status": "exhibition"
  }  ,
  {
    "id": "17",
    "title": "Painting 18",
    "artist": "Artist 18",
    "artistBio": "Bio for 18",
    "category": "Classical",
    "styleName": "Style",
    "styleDescription": "Description",
    "image": "/images/master/6a116929-859b-4896-8be3-dd56ab0ba2b7.jpeg",
    "description": "A masterpiece from master",
    "aiValuation": " - ",
    "startingPrice": 100000,
    "currentBid": 150000,
    "highBidder": "Collector_X",
    "timerSeconds": 120,
    "status": "auction"
  }  ,
  {
    "id": "18",
    "title": "Painting 19",
    "artist": "Artist 19",
    "artistBio": "Bio for 19",
    "category": "Classical",
    "styleName": "Style",
    "styleDescription": "Description",
    "image": "/images/master/8344a6ac-bb5f-4087-ad0a-a61ebd912a89.jpeg",
    "description": "A masterpiece from master",
    "aiValuation": " - ",
    "startingPrice": 100000,
    "currentBid": 150000,
    "highBidder": "Collector_X",
    "timerSeconds": 120,
    "status": "auction"
  }  ,
  {
    "id": "19",
    "title": "Painting 20",
    "artist": "Artist 20",
    "artistBio": "Bio for 20",
    "category": "Classical",
    "styleName": "Style",
    "styleDescription": "Description",
    "image": "/images/master/classical-art-inspiration-v0-2yw9cgy01h5f1.webp",
    "description": "A masterpiece from master",
    "aiValuation": " - ",
    "startingPrice": 100000,
    "currentBid": 0,
    "highBidder": "None",
    "timerSeconds": 0,
    "status": "exhibition"
  }  ,
  {
    "id": "20",
    "title": "Painting 21",
    "artist": "Artist 21",
    "artistBio": "Bio for 21",
    "category": "Classical",
    "styleName": "Style",
    "styleDescription": "Description",
    "image": "/images/master/images.jpeg",
    "description": "A masterpiece from master",
    "aiValuation": " - ",
    "startingPrice": 100000,
    "currentBid": 0,
    "highBidder": "None",
    "timerSeconds": 0,
    "status": "exhibition"
  }  ,
  {
    "id": "21",
    "title": "Painting 22",
    "artist": "Artist 22",
    "artistBio": "Bio for 22",
    "category": "Classical",
    "styleName": "Style",
    "styleDescription": "Description",
    "image": "/images/master/istockphoto-157482225-612x612.jpg",
    "description": "A masterpiece from master",
    "aiValuation": " - ",
    "startingPrice": 100000,
    "currentBid": 0,
    "highBidder": "None",
    "timerSeconds": 0,
    "status": "exhibition"
  }  ,
  {
    "id": "22",
    "title": "Painting 23",
    "artist": "Artist 23",
    "artistBio": "Bio for 23",
    "category": "Classical",
    "styleName": "Style",
    "styleDescription": "Description",
    "image": "/images/master/WhatsApp Image 2026-04-24 at 1.54.34 PM.jpeg",
    "description": "A masterpiece from master",
    "aiValuation": " - ",
    "startingPrice": 100000,
    "currentBid": 0,
    "highBidder": "None",
    "timerSeconds": 0,
    "status": "exhibition"
  }  ,
  {
    "id": "23",
    "title": "Painting 24",
    "artist": "Artist 24",
    "artistBio": "Bio for 24",
    "category": "Classical",
    "styleName": "Style",
    "styleDescription": "Description",
    "image": "/images/master/WhatsApp Image 2026-04-24 at 1.55.11 PM.jpeg",
    "description": "A masterpiece from master",
    "aiValuation": " - ",
    "startingPrice": 100000,
    "currentBid": 0,
    "highBidder": "None",
    "timerSeconds": 0,
    "status": "exhibition"
  }  ,
  {
    "id": "24",
    "title": "Painting 25",
    "artist": "Artist 25",
    "artistBio": "Bio for 25",
    "category": "Modern",
    "styleName": "Style",
    "styleDescription": "Description",
    "image": "/images/modern/WhatsApp Image 2026-04-24 at 1.47.43 PM.jpeg",
    "description": "A masterpiece from modern",
    "aiValuation": " - ",
    "startingPrice": 100000,
    "currentBid": 150000,
    "highBidder": "Collector_X",
    "timerSeconds": 120,
    "status": "auction"
  }  ,
  {
    "id": "25",
    "title": "Painting 26",
    "artist": "Artist 26",
    "artistBio": "Bio for 26",
    "category": "Modern",
    "styleName": "Style",
    "styleDescription": "Description",
    "image": "/images/modern/WhatsApp Image 2026-04-24 at 1.48.02 PM.jpeg",
    "description": "A masterpiece from modern",
    "aiValuation": " - ",
    "startingPrice": 100000,
    "currentBid": 150000,
    "highBidder": "Collector_X",
    "timerSeconds": 120,
    "status": "auction"
  }  ,
  {
    "id": "26",
    "title": "Painting 27",
    "artist": "Artist 27",
    "artistBio": "Bio for 27",
    "category": "Modern",
    "styleName": "Style",
    "styleDescription": "Description",
    "image": "/images/modern/WhatsApp Image 2026-04-24 at 1.48.22 PM.jpeg",
    "description": "A masterpiece from modern",
    "aiValuation": " - ",
    "startingPrice": 100000,
    "currentBid": 0,
    "highBidder": "None",
    "timerSeconds": 0,
    "status": "exhibition"
  }  ,
  {
    "id": "27",
    "title": "Painting 28",
    "artist": "Artist 28",
    "artistBio": "Bio for 28",
    "category": "Modern",
    "styleName": "Style",
    "styleDescription": "Description",
    "image": "/images/modern/WhatsApp Image 2026-04-24 at 1.48.40 PM.jpeg",
    "description": "A masterpiece from modern",
    "aiValuation": " - ",
    "startingPrice": 100000,
    "currentBid": 0,
    "highBidder": "None",
    "timerSeconds": 0,
    "status": "exhibition"
  }  ,
  {
    "id": "28",
    "title": "Painting 29",
    "artist": "Artist 29",
    "artistBio": "Bio for 29",
    "category": "Modern",
    "styleName": "Style",
    "styleDescription": "Description",
    "image": "/images/modern/WhatsApp Image 2026-04-24 at 1.49.45 PM.jpeg",
    "description": "A masterpiece from modern",
    "aiValuation": " - ",
    "startingPrice": 100000,
    "currentBid": 0,
    "highBidder": "None",
    "timerSeconds": 0,
    "status": "exhibition"
  }  ,
  {
    "id": "29",
    "title": "Painting 30",
    "artist": "Artist 30",
    "artistBio": "Bio for 30",
    "category": "Modern",
    "styleName": "Style",
    "styleDescription": "Description",
    "image": "/images/modern/WhatsApp Image 2026-04-24 at 1.50.55 PM (1).jpeg",
    "description": "A masterpiece from modern",
    "aiValuation": " - ",
    "startingPrice": 100000,
    "currentBid": 0,
    "highBidder": "None",
    "timerSeconds": 0,
    "status": "exhibition"
  }  ,
  {
    "id": "30",
    "title": "Painting 31",
    "artist": "Artist 31",
    "artistBio": "Bio for 31",
    "category": "Modern",
    "styleName": "Style",
    "styleDescription": "Description",
    "image": "/images/modern/WhatsApp Image 2026-04-24 at 1.50.55 PM.jpeg",
    "description": "A masterpiece from modern",
    "aiValuation": " - ",
    "startingPrice": 100000,
    "currentBid": 0,
    "highBidder": "None",
    "timerSeconds": 0,
    "status": "exhibition"
  }  ,
  {
    "id": "31",
    "title": "Painting 32",
    "artist": "Artist 32",
    "artistBio": "Bio for 32",
    "category": "Modern",
    "styleName": "Style",
    "styleDescription": "Description",
    "image": "/images/modern/WhatsApp Image 2026-04-24 at 1.50.56 PM (1).jpeg",
    "description": "A masterpiece from modern",
    "aiValuation": " - ",
    "startingPrice": 100000,
    "currentBid": 0,
    "highBidder": "None",
    "timerSeconds": 0,
    "status": "exhibition"
  }  ,
  {
    "id": "32",
    "title": "Painting 33",
    "artist": "Artist 33",
    "artistBio": "Bio for 33",
    "category": "Modern",
    "styleName": "Style",
    "styleDescription": "Description",
    "image": "/images/modern/WhatsApp Image 2026-04-24 at 1.50.56 PM (2).jpeg",
    "description": "A masterpiece from modern",
    "aiValuation": " - ",
    "startingPrice": 100000,
    "currentBid": 0,
    "highBidder": "None",
    "timerSeconds": 0,
    "status": "exhibition"
  }  ,
  {
    "id": "33",
    "title": "Painting 34",
    "artist": "Artist 34",
    "artistBio": "Bio for 34",
    "category": "Modern",
    "styleName": "Style",
    "styleDescription": "Description",
    "image": "/images/modern/WhatsApp Image 2026-04-24 at 1.50.56 PM.jpeg",
    "description": "A masterpiece from modern",
    "aiValuation": " - ",
    "startingPrice": 100000,
    "currentBid": 0,
    "highBidder": "None",
    "timerSeconds": 0,
    "status": "exhibition"
  }  ,
  {
    "id": "34",
    "title": "Painting 35",
    "artist": "Artist 35",
    "artistBio": "Bio for 35",
    "category": "Modern",
    "styleName": "Style",
    "styleDescription": "Description",
    "image": "/images/modern/WhatsApp Image 2026-04-24 at 1.50.57 PM (1).jpeg",
    "description": "A masterpiece from modern",
    "aiValuation": " - ",
    "startingPrice": 100000,
    "currentBid": 0,
    "highBidder": "None",
    "timerSeconds": 0,
    "status": "exhibition"
  }  ,
  {
    "id": "35",
    "title": "Painting 36",
    "artist": "Artist 36",
    "artistBio": "Bio for 36",
    "category": "Modern",
    "styleName": "Style",
    "styleDescription": "Description",
    "image": "/images/modern/WhatsApp Image 2026-04-24 at 1.50.57 PM.jpeg",
    "description": "A masterpiece from modern",
    "aiValuation": " - ",
    "startingPrice": 100000,
    "currentBid": 0,
    "highBidder": "None",
    "timerSeconds": 0,
    "status": "exhibition"
  }
];

export const INITIAL_USER_VAULT = [
  {
    id: 'user-1',
    title: 'Ethereal Flow',
    artist: 'Isabella Moretti',
    artistBio: 'Trained in Florence, Moretti captures the spiritual essence of the Mediterranean horizon.',
    category: 'Classical',
    styleName: 'Mediterranean Luminism',
    styleDescription: 'An emphasis on atmospheric tranquility and the specific quality of seaside light.',
    image: 'https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?q=80&w=1000&auto=format&fit=crop',
    description: 'One of Moretti’s early studies on liquid motion.',
    aiValuation: '$450k',
    startingPrice: 300000,
    currentBid: 0,
    highBidder: 'Me',
    timerSeconds: 0,
    status: 'sold',
    purchasePrice: 380000,
    currentMarketValue: 450000
  },
  {
    id: 'user-2',
    title: 'Sub-Zero Pulse',
    artist: 'ELXRA',
    artistBio: 'A digital pioneer based in Tokyo, ELXRA blends biometric data with algorithmic aesthetics.',
    category: 'Modern',
    styleName: 'Neo-Digitalism',
    styleDescription: 'A movement where code and canvas merge, emphasizing the vibrant, glowing nature of digital existence.',
    image: 'https://images.unsplash.com/photo-1633167606207-d840b5070fc2?q=80&w=1000&auto=format&fit=crop',
    description: 'A study in minimalist blue tones from the Arctic series.',
    aiValuation: '$220k',
    startingPrice: 150000,
    currentBid: 0,
    highBidder: 'Me',
    timerSeconds: 0,
    status: 'sold',
    purchasePrice: 240000,
    currentMarketValue: 220000
  }
];
